---
run:
  deadline: 5m
  skip-dirs:
    - proto
  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - exportloopref
    - gocritic
    - gofumpt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
  fast: false