name: build package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@master
      with:
        go-version: 1.18.4
        check-latest: true
        cache: true

    # - uses: actions/download-artifact@master
    #   id: download
    #   with:
    #     name: proto
    #     path: proto
    # - run: |
    #     ls
    #     ls ./pkg/stockbroker/service/tinkoffbroker/proto
    #     cp -rf ${{steps.download.outputs.download-path}}/* ./pkg/stockbroker/service/tinkoffbroker/proto
    #     ls ./pkg/stockbroker/service/tinkoffbroker/proto

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: make build

    - name: Run go vet
      run: make vet

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck .

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./cmd/tinkoffbroker/

    - name: Run tests
      run: go test -race -vet=off ./cmd/tinkoffbroker/

    - name: Send telegram message on push with job ststus success
      if: ${{ success() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHANNEL }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
          
            Repository: ${{ github.repository }}
            Build: ${{ github.job }} job in workflow ${{ github.workflow }}
            Status: ${{ job.status }} ✅

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

    - name: Send telegram message on push with job ststus failure
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHANNEL }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
          
            Repository: ${{ github.repository }}
            Build: ${{ github.job }} job in workflow ${{ github.workflow }}
            Status: ${{ job.status }} 🛑

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}